#! /usr/bin/env sh

# Pi-hole_SafeSearch.sh --enable

set -e

setDomains() {
  if [[ $1 != "" ]]; then
    pihole --wild $1 -q
  fi
}

domains=""
i=0

while read thisDomain; do
  domains="$domains $thisDomain"
  if [[ $i == 9 ]]; then
    setDomains $domains
    domains=""
    i=0
  else
    i=$(($i + 1))
  fi
done <domains.txt

setDomains $domains

pihole restartdns >/dev/null

echo "\e[32m[success] enabled\e[0m"
