#! /usr/bin/env sh

# Pi-hole_SafeSearch.sh --disable

set -e

setDomains() {
  if [[ $1 != "" ]]; then
    pihole -b -d $1
    pihole --wild -d $1
  fi
}

fname=$1
if [[ $fname == "" ]]; then
  fname="domains.txt"
fi
domains=""
i=0

while read thisDomain; do
  domains="$domains $thisDomain"
  if [[ $i == 9 ]]; then
    setDomains "$domains"
    domains=""
    i=0
  else
    i=$(($i + 1))
  fi
done <$fname

setDomains $domains

pihole restartdns

echo -e "[\e[32m*\e[0m] Disabled"
